#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Zsh
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

# Neovim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim


# Tmux
ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

#ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig

#ln -sf $DOTFILES/git/gitignore_global $HOME/.gitignore_global

#rm -rf $HOME/.config/phpactor
#ln -s $DOTFILES/phpactor $HOME/.config/phpactor

# Phpactor
rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/phpactor $HOME/.config/phpactor

# Scripts
mkdir -p $HOME/.local/bin

rm -rf $HOME/.local/bin/t
rm -rf $HOME/.local/bin/sshhost
ln -sf $DOTFILES/scripts/t $HOME/.local/bin/t
ln -sf $DOTFILES/scripts/sshhost $HOME/.local/bin/sshhost
#ln -sf $DOTFILES/scripts/deliver $HOME/.local/bin/deliver

#mkdir -p $HOME/.nvm
#ln -sf $DOTFILES/nvm/default-packages $HOME/.nvm/default-packages

# Oh My Zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi


