#!/usr/bin/sh

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

echo $COMMIT_SOURCE >> ~/commit_source.txt

unhandledSources=("merge" "squash" "commit")

if ! [[ -z $COMMIT_SOURCE ]] && [[ ${unhandledSources[@]} =~ $COMMIT_SOURCE ]]
then
    exit 0
fi

taskId=$(git rev-parse --abbrev-ref HEAD | awk -F "[/_]" '{print $2}')

action=$(echo "BUGFIX, FEATURE, CLEANUP, REFACTOR, INSPECTIONS" | sed "s/, /\n/g" | fzf)

commitMessage="#${taskId}: [${action}] "

origMessage=$(cat $COMMIT_MSG_FILE)
echo "${commitMessage}${origMessage}" > $COMMIT_MSG_FILE
